# CSE 232B — XQuery Processor, Milestone 1 (XPath)
#
# Targets:
#   make            generate ANTLR parser + compile everything
#   make parser     only regenerate parser (after editing XPath.g4)
#   make run Q='...'  run a query; example: make run Q='doc("test.xml")/library/book'
#   make clean      delete generated + compiled files

ANTLR_JAR = antlr-4.13.2-complete.jar
CP        = .:$(ANTLR_JAR)
JFLAGS    = -g

# Java sources that YOU write (engine + driver).
HAND_SRCS = XPathEngine.java Main.java

# Java sources GENERATED by ANTLR from XPath.g4.
GEN_SRCS  = XPathLexer.java XPathParser.java XPathVisitor.java XPathBaseVisitor.java

all: classes

# Regenerate the parser/lexer/visitor from the grammar.
parser: $(GEN_SRCS)

$(GEN_SRCS): XPath.g4
	java -jar $(ANTLR_JAR) -visitor -no-listener XPath.g4

# Compile everything into .class files in this directory.
classes: parser
	javac $(JFLAGS) -cp $(CP) $(GEN_SRCS) $(HAND_SRCS)

# Quick run. Override Q on the command line.
Q ?= doc("test.xml")/library/book
run: classes
	java -cp $(CP) Main '$(Q)'

clean:
	rm -f *.class *.interp *.tokens
	rm -f $(GEN_SRCS)

.PHONY: all parser classes run clean
